---
version: '3.1'
services:
  mongo:
    container_name: mongo
    build:
      mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hackerman
    command: [--auth]
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: